### PR TITLE
Curriculum fr

### PR DESCRIPTION
**Pull request by davidkathoh**

### CODE REVIEW

**Comment by BracketCove** [comment]
Looks great; thanks!

**Comment by davidkathoh** [comment]
Welcome.

**Comment by BracketCove** [comment]
Hi David,

I've updated the formatting for the creators section. If you would like to submit a PR for the Contributors section, I'd be happy to add you in. Please use the format described Contribution Guide.

Cheers

**Comment by davidkathoh** [comment]
I really appreciate that I'm submitting a PR

**Pull request merged**
